version: "2"
services:

  vertcoind:
    image: lukechilds/vertcoind
    expose:
      - "5888"
    ports:
      - "5889:5889"
    volumes:
      - ./data/vertcoind:/data
    command: -rpcuser=electrum -rpcpassword=electrum

  electrumx:
    image: lukechilds/electrumx
    ports:
      - "55002:50002"
    volumes:
      - ./data/electrumx:/data
    environment:
      - DAEMON_URL=http://electrum:electrum@vertcoind:5888
      - COIN=Vertcoin
